# Generated by Django 4.2.1 on 2023-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
