# Generated by Django 4.2.1 on 2023-07-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_emp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
