# Generated by Django 4.2.1 on 2023-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_employed_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_score',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_employed',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employed_joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
