# Generated by Django 4.2.1 on 2023-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_employee_emp_salary_remove_employee_emp_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
