# Generated by Django 4.2.1 on 2023-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_emp_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_files',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employed_joining_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_profile',
            field=models.ImageField(blank=True, null=True, upload_to='emp_profile_pics/'),
        ),
    ]
