# Generated by Django 4.2.1 on 2023-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_employee_emp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_url',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
