# Generated by Django 4.2.1 on 2023-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_employee_emp_profile_remove_employee_emp_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
