# Generated by Django 4.2.1 on 2023-09-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_position_employee_emp_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_position',
        ),
    ]
